local opt = vim.opt
opt.nu = true
opt.rnu = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.expandtab = true
opt.backup = false
opt.scrolloff = 10
opt.ignorecase = true
opt.smartcase = true
opt.smartindent = true
opt.swapfile = false
opt.cul = true
opt.colorcolumn = '80'
